[package]
name = "cloud-sync-point"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", features = ["macros"] }
dashmap = "6.1.0"
tokio = { version = "1.41.1", features = ["full"] }
